# Generated by Django 4.2.1 on 2023-05-28 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=127)),
                ('id_user', models.CharField(max_length=127, primary_key=True, serialize=False)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=127)),
            ],
        ),
    ]
