# Generated by Django 4.2.1 on 2023-05-29 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id_user',
            field=models.CharField(max_length=127),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=127),
        ),
    ]
