# Generated by Django 4.2.1 on 2023-05-29 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('codigo_IATA_aerolinea', models.CharField(max_length=45, primary_key=True, serialize=False, unique=True)),
                ('nombre_aerolinea', models.CharField(max_length=127)),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('codigo_IATA_aeropuerto', models.CharField(max_length=45, primary_key=True, serialize=False, unique=True)),
                ('nombre_aeropuerto', models.CharField(max_length=127)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id_ciudad', models.CharField(max_length=45, primary_key=True, serialize=False, unique=True)),
                ('nombre_ciudad', models.CharField(max_length=127)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id_pais', models.CharField(max_length=45, primary_key=True, serialize=False, unique=True)),
                ('nombre_pais', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id_ticket', models.CharField(max_length=45, primary_key=True, serialize=False, unique=True)),
                ('grupo', models.CharField(max_length=45)),
                ('asiento', models.CharField(max_length=45)),
                ('categoria_pasajero', models.CharField(max_length=45)),
                ('equipaje_mano', models.FloatField()),
                ('equipaje_bodega', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id_vuelo', models.CharField(max_length=45, primary_key=True, serialize=False, unique=True)),
                ('fecha_salida', models.DateTimeField()),
                ('fecha_llegada', models.DateTimeField()),
                ('categoria_vuelo', models.CharField(choices=[('NATIONAL_FLIGHT', 'National Flight'), ('INTERNATIONAL_FLIGHT', 'International Flight'), ('REGIONAL_FLIGHT', 'Regional Flight')], max_length=45)),
                ('codigo_IATA_aerolinea_vuelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.airline')),
                ('codigo_IATA_aeropuerto_llegada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigo_IATA_aeropuerto_llegada', to='flight.airport')),
                ('codigo_IATA_aeropuerto_salida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigo_IATA_aeropuerto_salida', to='flight.airport')),
                ('id_ciudad_aeropuerto_llegada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_ciudad_aeropuerto_llegada', to='flight.city')),
                ('id_ciudad_aeropuerto_salida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_ciudad_aeropuerto_salida', to='flight.city')),
                ('id_pais_aeropuerto_llegada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_pais_aeropuerto_llegada', to='flight.country')),
                ('id_pais_aeropuerto_salida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_pais_aeropuerto_salida', to='flight.country')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='id_pais_ciudad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.country'),
        ),
        migrations.AddField(
            model_name='airport',
            name='id_ciudad_aeropuerto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.city'),
        ),
        migrations.AddField(
            model_name='airport',
            name='id_pais_aeropuerto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.country'),
        ),
    ]
