# Generated by Django 4.2.1 on 2023-05-29 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id_ticket', models.CharField(max_length=45, primary_key=True, serialize=False, unique=True)),
                ('grupo', models.CharField(max_length=45)),
                ('asiento', models.CharField(max_length=45)),
                ('categoria_pasajero', models.CharField(max_length=45)),
                ('equipaje_mano', models.FloatField()),
                ('equipaje_bodega', models.FloatField()),
                ('codigo_IATA_aerolinea_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.airline')),
                ('codigo_IATA_aeropuerto_llegada_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigo_IATA_aeropuerto_llegada_ticket', to='flight.airport')),
                ('codigo_IATA_aeropuerto_salida_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigo_IATA_aeropuerto_salida_ticket', to='flight.airport')),
                ('id_ciudad_aeropuerto_llegada_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_ciudad_aeropuerto_llegada_ticket', to='flight.city')),
                ('id_ciudad_aeropuerto_salida_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_ciudad_aeropuerto_salida_ticket', to='flight.city')),
                ('id_pais_aeropuerto_llegada_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_pais_aeropuerto_llegada_ticket', to='flight.country')),
                ('id_pais_aeropuerto_salida_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_pais_aeropuerto_salida_ticket', to='flight.country')),
                ('id_vuelo_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.flight')),
            ],
        ),
    ]
