# Generated by Django 4.2.1 on 2023-05-29 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0002_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='codigo_IATA_aerolinea_ticket',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='codigo_IATA_aeropuerto_llegada_ticket',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='codigo_IATA_aeropuerto_salida_ticket',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='id_ciudad_aeropuerto_llegada_ticket',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='id_ciudad_aeropuerto_salida_ticket',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='id_pais_aeropuerto_llegada_ticket',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='id_pais_aeropuerto_salida_ticket',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='id_vuelo_ticket',
        ),
    ]
