# Generated by Django 4.2.1 on 2023-05-29 05:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flight', '0003_remove_ticket_codigo_iata_aerolinea_ticket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='id_vuelo_ticket',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='flight.flight'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='username_ticket',
            field=models.ForeignKey(default='none', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
