# Generated by Django 4.2.1 on 2023-05-29 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0004_ticket_id_vuelo_ticket_ticket_username_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='id_vuelo_ticket',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='username_ticket',
        ),
    ]
